language: node_js
node_js:
  - "8"
addons:
  chrome: stable
before_install:
  - echo 'installing dependencies'
  - sudo apt-get install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - echo 'Installing chrome driver'
  - wget -N http://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - echo 'installing npm packages'
  - npm install
script:
  # while the dev server is starting we do the rest of the work
  - npm run build
  - npm run lint
  - npm run test
  - npm run e2e
