language: node_js
node_js:
  - "8"
addons:
  chrome: stable
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable


before_install:
  - echo 'installing dependencies'
  - sudo apt-get install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - echo 'installing npm packages'
  - npm install

script: npm run test:unit

cache: npm

env:
  - BASE_URL=/liwo

matrix:
  fast_finish: true

jobs:
  include:
    - stage: test
      # run the following with basurl root
      script: npm run lint && npm run test:unit
    - stage: build
      script: npm run build && tar -czf liwo.tar.gz dist && zip -r liwo.zip dist
    - stage: release
      script: npm run release
    - stage: deploy
      script: npm run build && tar -czf liwo.tar.gz dist && zip -r liwo.zip dist
      deploy:
        - provider: releases
          api_key:
            secure: $GITHUB_TOKEN
          file:
            - liwo.tar.gz
            - liwo.zip
          skip_cleanup: true
          on:
            tags: true
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
          keep-history: true
          local-dir: dist
          on:
            branch: master
stages:
  - test
  - build
  - release
  - deploy
