language: node_js
node_js:
  - "8"
addons:
  chrome: stable
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable


before_install:
  - echo 'installing dependencies'
  - sudo apt-get install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - echo 'installing npm packages'
  - npm install
script:
  # while the dev server is starting we do the rest of the work
  - npm run build
  - npm run lint
  - npm run test
  - npm run e2e
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
