import { createApp } from 'vue'
import App from './App.vue'

import leafletDirective from './lib/leaflet-directive'
import VueSkipTo from '@vue-a11y/skip-to'
import router from './router'
import store from './store'
import VueHead from 'vue-head'
import PortalVue from 'portal-vue'

import VueMatomo from 'vue-matomo'

// Babel JS switched to core-js
import 'core-js/stable'
import 'regenerator-runtime/runtime'

import 'whatwg-fetch'
import 'url-polyfill'
import 'proxy-polyfill'

// e.g. in app.ts
import mitt from 'mitt'

const emitter = mitt()

const app = createApp(App)

app.config.globalProperties.$emitter = emitter

app.config.productionTip = false
app.directive('leaflet', leafletDirective)
app.use(VueHead)
app.use(VueSkipTo)
app.use(PortalVue)

app.use(router)
app.use(store)

app.use(VueMatomo, {
  // Configure your matomo server and site by providing
  host: 'https://statistiek.rijksoverheid.nl',
  siteId: process.env.VUE_APP_MATOMO_SITE_ID,

  // Changes the default .js and .php endpoint's filename
  // Default: 'matomo'
  trackerFileName: 'matomo',

  // Overrides the autogenerated tracker endpoint entirely
  // Default: undefined
  // trackerUrl: 'https://example.com/whatever/endpoint/you/have',

  // Overrides the autogenerated tracker script path entirely
  // Default: undefined
  // trackerScriptUrl: 'https://example.com/whatever/script/path/you/have',

  // Enables automatically registering pageviews on the router
  router: router,

  // Enables link tracking on regular links. Note that this won't
  // work for routing links (ie. internal Vue router links)
  // Default: true
  enableLinkTracking: true,

  // Require consent before sending tracking information to matomo
  // Default: false
  configConsentRequired: true,

  // Whether to track the initial page view
  // Default: true
  trackInitialView: true,

  // Run Matomo without cookies
  // Default: false
  disableCookies: false,

  // Enable the heartbeat timer (https://developer.matomo.org/guides/tracking-javascript-guide#accurately-measure-the-time-spent-on-each-page)
  // Default: false
  enableHeartBeatTimer: false,

  // Set the heartbeat timer interval
  // Default: 15
  heartBeatTimerInterval: 15,

  // Whether or not to log debug information
  // Default: false
  debug: true,

  // Share the tracking cookie across subdomains (see https://developer.matomo.org/guides/tracking-javascript-guide#measuring-domains-andor-sub-domains)
  // Default: undefined, example '*.example.com'
  cookieDomain: undefined,

  // Tell Matomo the website domain so that clicks on these domains are not tracked as 'Outlinks'
  // Default: undefined, example: '*.example.com'
  domains: '*.basisinformatie-overstromingen.nl',

  // A list of pre-initialization actions that run before matomo is loaded
  // Default: []
  // Example: [
  //   ['API_method_name', parameter_list],
  //   ['setCustomVariable','1','VisitorType','Member'],
  //   ['appendToTrackingUrl', 'new_visit=1'],
  //   etc.
  // ]
  preInitActions: []
})

app.directive('test', {
  beforeMount (el, binding) {
    setAttribute(el, binding)
  },
  updated (el, binding) {
    setAttribute(el, binding)
  }
})

function setAttribute (el, binding) {
  if (binding.value !== false) {
    el.setAttribute('data-test', binding.value)
  }
}

app.mount('#app')

export default app
